# env_shell_expand enabled by default
# https://github.com/jdx/mise/releases/tag/v2026.7.0
min_version = "2026.7.0"

[settings.task]
output = "keep-order"

[tasks.lint]
depends = ["lint:*", "fmt:justfile --check"]

[tasks."lint:expl3"]
description = "Lint expl3 code"
alias = "explcheck"
env.EXPLCHECK_CONFIG = "{{ get_env(name='EXPLCHECK_CONFIG', default='config/explcheck.toml') }}"
# a) the glob file list is composed in the file inclusion pattern, in
#    pre-commit config too,
# b) explcheck allows intermixing optional arguments with positional
#    arguments, so extra arguments can be passed when invoking the task
run = """
explcheck \
  --config-file "$EXPLCHECK_CONFIG" \
  zutil/*.sty zutil/*.tex support/*.cfg
"""
interactive = true

[tasks."fmt:justfile"]
description = "Format justfiles"
alias = "justfile"
run = "just --fmt"
interactive = true

[tasks."lint:python"]
description = "Lint python code"
alias = "ruff"
dir = "l3build-wrapper"
usage = """
arg "[command]" default="check"
"""
run = "ruff {{ usage.command }}"
interactive = true

[tasks."lint:toml"]
description = "Lint TOML files"
alias = "tombi"
run = "tombi lint"

[tasks."lint:typos"]
description = "Check spelling"
alias = "typos"
run = "typos --config=config/typos.toml"

[tasks."lint:pre-commit"]
description = "Run pre-commit checks on all files"
alias = "pre-commit"
# the list of skipped hooks is composed in the `ci.skip` item, in pre-commit
# config too
env.SKIP = """
{{ get_env(name='SKIP', default='justfile,typos,explcheck,ruff,tombi') }}"""
run = [
  'echo "Skipped checks: {{ env.SKIP }}"',
  "pre-commit run --all-files --color=always"
]
interactive = true
