# env_shell_expand enabled by default
# https://github.com/jdx/mise/releases/tag/v2026.7.0
min_version = "2026.7.0"

[settings.task]
output = "keep-order"

[env]
# l3build env vars
diffext = { default = ".diff" }
diffexe = { default = "git diff --no-index --text --" }

[tasks.lint]
depends = ["lint:*"]

[tasks."lint:expl3"]
description = "Lint expl3 code"
alias = "explcheck"
env.EXPLCHECK_CONFIG = { default = "config/explcheck.toml" }
interactive = true
# a) the glob file list is composed in the file inclusion pattern, in
#    pre-commit config too,
# b) explcheck allows intermixing optional arguments with positional
#    arguments, so extra arguments can be passed when invoking the task
run = """
explcheck \
  --config-file "$EXPLCHECK_CONFIG" \
  zutil/*.sty zutil/*.tex support/*.cfg
"""

[tasks."lint:python"]
description = "Lint python code"
alias = "ruff"
dir = "l3build-wrapper"
interactive = true
usage = """
arg "[command]" default="check"
"""
run = "ruff {{ usage.command }}"

[tasks."lint:toml"]
description = "Lint TOML files"
alias = "tombi"
run = "tombi lint"

[tasks."lint:typos"]
description = "Check spelling"
alias = "typos"
run = "typos --config=config/typos.toml"

[tasks."lint:pre-commit"]
description = "Run pre-commit checks on all files"
alias = "pre-commit"
# the list of skipped hooks is composed in the `ci.skip` item, in pre-commit
# config too
env.SKIP = { default = "typos,explcheck,ruff,tombi" }
interactive = true
run = '''
#!/usr/bin/env bash
echo "Skipped checks: {{ env.SKIP }}"
pre-commit run --all-files --color=always
'''

[tasks.test]
depends = ["L3BUILD_MODULE=zutil test:check"]

[tasks.test-inactive]
# must run in series
run = [
  { task = "test:check", env = { L3BUILD_MODULE = "tblr" } },
  { task = "test:check", env = { L3BUILD_MODULE = "tblr-old" } },
  { task = "test:tblr-ppm" },
]

[tasks."test:tblr-ppm"]
dir = "tabularray"
run = '''
#!/usr/bin/env bash
echo "Running tblr-ppm tests, \"config-old\" config..."
texlua buildend.lua
'''

[tasks."test:check"]
alias = "check"
env.L3BUILD_CHECK_OPTIONS = { default = "-q --show-saves" }
interactive = true
# use Tera templates to get clean task header in output
run = '''
#!/usr/bin/env bash
{% if env.L3BUILD_MODULE is defined and env.L3BUILD_MODULE != "" %}
echo "[{{ env. MISE_TASK_NAME }}] Checking l3build tests for module \"{{ env.L3BUILD_MODULE }}\"..."
l3build-wrapper check {{ env.L3BUILD_CHECK_OPTIONS }} {{ env.L3BUILD_MODULE }} "$@"
{% else %}
l3build-wrapper check {{ env.L3BUILD_CHECK_OPTIONS }} "$@"
{% endif %}
'''

[tasks."test:save"]
alias = "save"
env.L3BUILD_SAVE_OPTIONS = { default = "-q" }
run = '''
l3build-wrapper save {{ env.L3BUILD_SAVE_OPTIONS }}
'''

[tasks."dev:new-test"]
description = "Create a new l3build test from template"
usage = """
arg "module"
arg "name"
"""
run = '''
#!/usr/bin/env bash
echo "Creating new l3build test \"$usage_module-$usage_name.lvt\" for module \"$usage_module\"..."
template="support/TEMPLATE-$usage_module-test.lvt"
new_test="$usage_module/testfiles/$usage_module-$usage_name.lvt"
if [[ ! -f "$template" ]]; then
  echo "Template file \"$template\" does not exist"
  exit 1
fi
if [[ -f "$new_test" ]]; then
  echo "Test file \"$new_test\" already exists."
  exit 1
fi
cp "$template" "$new_test"
code "$new_test"
'''

[tasks."dev:install-wrapper"]
description = "Reinstall l3build-wrapper in editable mode"
run = '''
#!/usr/bin/env bash
echo "Reinstalling l3build-wrapper in editable mode..."
cd l3build-wrapper && uv tool install --reinstall -e .
'''
