[settings]
env_shell_expand = true

[settings.task]
output = "keep-order"

[tasks.lint]
depends = ['lint:*', 'fmt:justfile --check']

[tasks."lint:expl3"]
description = 'Lint expl3 code'
alias = 'explcheck'
# tabularry is not checked
vars.filelist = 'zutil/*.sty zutil/*.tex support/*.cfg'
# Thanks to explcheck's CLI parsing which supports intermixed args. Otherwise
# a second task is needed.
run = 'explcheck-wrapper --config-file config/explcheck.toml {{ vars.filelist }}'
interactive = true

[tasks."fmt:justfile"]
description = 'Format justfiles'
alias = 'justfile'
run = 'just --fmt'
interactive = true

[tasks."lint:python"]
description = 'Lint python code'
alias = 'ruff'
dir = 'l3build-wrapper'
usage = '''
arg "[command]" default="check"
'''
run = 'ruff {{ usage.command }}'
interactive = true

[tasks."lint:typos"]
description = "Check spelling"
alias = 'typos'
run = 'typos --config=config/typos.toml'

[tasks."lint:pre-commit"]
description = "Run pre-commit checks on all files"
alias = 'pre-commit'
env.SKIP = '{{ get_env(name="SKIP", default="typos,justfile,explcheck,ruff") }}'
run = [
  'echo "Skipped checks: {{ env.SKIP }}"',
  'pre-commit run --all-files --color=always'
]
interactive = true
