include = ['l3build-wrapper/*.py']

target-version = 'py310'

[lint]
# https://docs.astral.sh/ruff/settings/#lint
select = ['ALL']
ignore = [
  'D107',   # undocumented public `__init__()` method
  'D203',   # class docstring not preceded by a blank line,
            #   incompatible with D211
  'D213',   # the (first) summary line of multi-line docstrings not on the
            #   second physical line, incompatible with D212
  'T201',   # uses of `print()`
  'TD002',  # Missing author in TODO
  'TD003',  # Missing issue link for this TODO
  'TRY400', # use `logging.error` instead of `logging.exception` when logging
            #   an exception
  'PGH004', # blanket `noqa` annotation which suppresses all diagnostics
]
# relatively temp ignorance
extend-ignore = [
  'COM812', # Trailing comma missing
            #   tracking issue https://github.com/astral-sh/ruff/issues/9216
  'FIX002', # Line contains TODO, consider resolving the issue
]
flake8-quotes.inline-quotes = 'single'

[format]
# https://docs.astral.sh/ruff/settings/#format
quote-style = 'single'
