# full list of explcheck configs, and their default values
# https://github.com/Witiko/expltools/blob/main/explcheck/src/explcheck-config.toml

[defaults]
stop_early_when_confused = false
warnings_are_errors = true

[filename."zutil-debug.code.tex"]
defined_csnames = [
  "zutil_debug:ne"
]
