name: Schedule

on:
  schedule:
    # at 12:21 UTC (20:21 CST/UTC +8) on every Friday
    # https://crontab.guru/#21_12_*_*_5
    - cron: "21 12 * * 5"
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yml
    with:
      images: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      update-cache: true
    permissions:
      actions: write
  lint:
    uses: ./.github/workflows/lint.yml
