name: Schedule

on:
  schedule:
    # at 12:21 UTC (20:21 CST/UTC +8) on every Thursday
    # https://crontab.guru/#21_12_*_*_4
    - cron: "21 12 * * 4"
  workflow_dispatch:
    inputs:
      install-texlive-cleanly:
        description: "Install TeX live from scratch?"
        required: false
        type: boolean
        default: true

jobs:
  check:
    permissions:
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      images: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      install-texlive-cleanly: ${{ inputs.install-texlive-cleanly || true}}
      test-tblr-old: true
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml
