name: Schedule

run-name: >-
  ${{ case(
    github.event_name == 'workflow_dispatch',
    format('Schedule ({0})', github.event_name),
    ''
  )}}

on:
  schedule:
    # at 12:21 UTC (20:21 CST/UTC +8) on every Thursday
    # https://crontab.guru/#21_12_*_*_4
    - cron: "21 12 * * 4"
  workflow_dispatch:
    inputs:
      install-texlive-cleanly:
        description: "Install TeX Live from scratch?"
        required: false
        type: boolean
        default: true
      l3build-check-extra-options:
        description: "Extra \"l3build check\" options, e.g., --dev"
        required: false
        type: string
        default: ""

jobs:
  check:
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    uses: $/.github/workflows/check.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      install-texlive-cleanly: ${{ inputs.install-texlive-cleanly || true }}
      l3build-check-extra-options: ${{ inputs.l3build-check-extra-options || '' }}
      # TODO: perhaps reenable this when `tabularray` resumes updates
      test-inactive: false

  lint:
    permissions:
      contents: read
    uses: $/.github/workflows/lint.yml
