# Based on https://github.com/CTeX-org/ctex-kit/blob/master/.github/workflows/test.yml

name: Test suite

on:
  pull_request:
    types:
      # added "ready_for_review"
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      [opened, ready_for_review, reopened, synchronize]
  push:
  schedule:
    # at 12:21 UTC (20:21 CST/UTC +8) on every Friday
    - cron: "21 12 * * 5"
  workflow_dispatch:

jobs:
  test-l3build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        # avoid "Cache already exists" warnings
        cache: false
        package-file: .github/workflows/texlive.package
        update-all-packages: true
    - name: Test tabularray with l3build
      run: |
        l3build check --halt-on-error --show-log-on-error

  test-ppmcheckpdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: .github/workflows/texlive.package
        update-all-packages: true
    - name: Install pdftoppm
      run: |
        sudo apt-get install poppler-utils
    - name: Prepare PDFTeX-generated PDFs for ppmcheckpdf
      # because existing .png and .md5 files are based on PDFTeX-generated PDFs
      run: |
        l3build check -epdftex --halt-on-error
    - name: Test tabularray with ppmcheckpdf
      run: |
        texlua buildend.lua
    - name: Upload png and md5
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: png-and-md5
        path: |
          testfiles/*.png
          testfiles/*.md5
