# Based on https://github.com/CTeX-org/ctex-kit/blob/master/.github/workflows/test.yml

name: Test suite

on:
  pull_request:
    types:
      # added "ready_for_review"
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      [opened, ready_for_review, reopened, synchronize]
  push:
  schedule:
    # at 12:21 UTC (20:21 CST/UTC +8) on every Friday
    - cron: "21 12 * * 5"
  workflow_dispatch:

jobs:
  tests-new:
    strategy:
      matrix:
        format: [latex, latex-dev]
    name: ${{ format('Tests ({0})', matrix.format) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: .github/workflows/texlive.package
        update-all-packages: true

    - name: Run tests
      run: |
        l3build check -cbuild --halt-on-error --show-saves \
          ${{ matrix.format == 'latex-dev' && '--dev' || '' }}

  tests-old:
    strategy:
      matrix:
        format: [latex, latex-dev]

    name: ${{ format('Old tests ({0})', matrix.format) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: .github/workflows/texlive.package
        update-all-packages: true
    - name: Install ppmcheckpdf dependencies
      run: |
        sudo apt-get install imagemagick poppler-utils

    # note: old tests in "./testfiles-old" are only checked using pdftex,
    # which is also the engine used to generate .png and .md5 files.
    - name: Run old tests with l3build
      run: |
        l3build check -cconfig-old --halt-on-error --show-saves \
          ${{ matrix.format == 'latex-dev' && '--dev' || '' }}

    - name: Run old tests with ppmcheckpdf
      id: ppmcheckpdf
      run: |
        texlua buildend.lua

    # TODO: generate a list of files related to failed tests, then
    # upload all them (.tex, .log, .pdf, .png, .md5, etc.)
    - name: Upload diff files
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: tabularray-diffs
        path: |
          build/**/*.diff
          build/**/*.diff.png
